services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/DockerfileFrontend
    container_name: angular-frontend
    ports:
      - "4203:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/DockerfileBackend
    container_name: nest-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
#    volumes:
#      - .:/app
#      - /app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
